export const Label = {
  EDIT_USER_TITLE : 'Edit User',
  ADD_USER_TITLE : 'Add User',
  ID : 'Id',
  NAME : 'Name',
  FIRST_NAME : 'First Name',
  LAST_NAME : 'Last Name',
  GENDER : 'Gender',
  USER_NAME : 'User Name',
  PASSWORD : 'Password',
  CONFIRM_PASSWORD : 'Confirm Password',
  USER_NOTIFICATION_TYPE : 'User Notification Type',
  EMAIL_ID : 'Email Id',
  MOBILE_NO : 'Mobile No.',
  ADDRESS : 'Address',
  ADDRESS_LINE1 : 'Address Line 1',
  ADDRESS_LINE2 : 'Address Line 2',
  COUNTRY : 'Country',
  STATE : 'State',
  CITY : 'City',
  ZIP_CODE : 'Zip Code',
  USER_STATUS : 'User Status',
  ACTION : 'Action',
  CAPTCHA : 'Captcha',
  SEARCH : 'Search',
  PAGE_SIZE_OPTION : [5,10,20,50,100]
}

export const Message = {
  ONLY_ADMIN_CAN_LOGIN : 'Only Admin can login',
  INVALID_CREDENTIALS : 'Invalid Credentials',
  SUBMIT_MSG : 'User submitted successfully',
  SUBMIT_ERROR_MSG: 'User submission failed',
  STATUS_CHANGED_MSG: 'User status changed successfully',
  STATUS_CHANGED_ERROR_MSG: 'Failed to change user status',
}

export const Validation = {
  REQUIRED: 'required',
  MIN_LENGTH_2: 'must be at least 2 characters',
  MIN_LENGTH_6: 'must be at least 6 characters',
  MIN_LENGTH_8: 'must be at least 8 characters',
  MAX_LENGTH_20: 'must not exceed 20 characters',
  FIX_LENGTH_6: 'should have 6 digits only',
  FIX_LENGTH_10: 'should have 10 digits only',
  ALLOWED_ONLY_NUMBERS: 'allowed only numbers',
  NOT_ALLOWED_NUMBERS: 'should not allowed numbers',
  NOT_ALLOWED_SPACE: 'should not allowed space',
  ALREADY_EXISTS: 'already exists',
  VALID_PASSWORD: 'must have at least one number, one lowercase, one uppercase and one special character',
  PASSWORD_MISMATCH: 'did not match with password',
  INVALID: 'not valid',
}
